defaults:  
  - _self_  
  - override hydra/job_logging: none #colorlog
  - override hydra/hydra_logging: none #colorlog

# paths: 
#   output_dir: ./results/vid

# hydra:
#   run:
#     dir: ./results/vid

video:
  source: ./data/demo/vid.mp4
  output_dir: results/vid
  start_frame: 0
  end_frame: 10
  output_resolution: 1440

phalp:
  predict: TPL
  distance_type: EQ_010
  alpha: 0.1
  low_th_c: 0.8
  hungarian_th: 100.0
  track_history: 7
  max_age_track: 20
  n_init: 1 #5
  encode_type: 4c
  past_lookback: 1
  detection_type: mask
  shot: 0
  start_frame: 0
  end_frame: 10

render:
  enable: True
  type: HUMAN_MESH # options: HUMAN_MESH, HUMAN_MASK, HUMAN_BBOX
  up_scale: 2
  res: 256

SMPL:
  MODEL_PATH: _DATA/models/smpl/
  GENDER: neutral
  MODEL_TYPE: smpl
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_H36M: _DATA/J_regressor_h36m.npy
  JOINT_REGRESSOR_EXTRA: _DATA/SMPL_to_J19.pkl
  TEXTURE: _DATA/texture.npz
MODEL:
  IMAGE_SIZE: 256
  SMPL_HEAD:
    TYPE: basic
    POOL: max
    SMPL_MEAN_PARAMS: _DATA/smpl_mean_params.npz
    IN_CHANNELS: 2048
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
    MASK_TYPE: feat
  TRANSFORMER:
    HEADS: 1
    LAYERS: 1
    BOX_FEATS: 6
  pose_transformer_size: 2048
    
EXTRA:
  FOCAL_LENGTH: 5000


experiment_name: demo
track_dataset: demo
device: "cuda"
train: False
debug: False
use_gt: False
overwrite: True
batch_id: -1
verbose: False
detect_shots: False

base_path: null
video_seq: null
